# ДЗ

#### 1. привести разл способы созд series

In [88]:
import pandas as pd
import numpy as np
a = pd.Series([9,8,3,4])
print(a) # список
b = pd.Series(np.random.randint(1,5,4))
print(b) # массив нампи
print(pd.Series(3, index=[1,2,3,4,5,6])) # из числа
print(pd.Series({'Sasha': 18, 'Masha': 19, 'Danya': 23}))



0    9
1    8
2    3
3    4
dtype: int64
0    2
1    2
2    4
3    3
dtype: int32
1    3
2    3
3    3
4    3
5    3
6    3
dtype: int64
Sasha    18
Masha    19
Danya    23
dtype: int64


### 2. Привести различные способы создания объектов DataFrame

In [89]:
df_1 = pd.DataFrame(a)
print(df_1)
dct_1 = {'first': [1,2,3,4], 'second': [5,6,8,9]}
dct_2 = {'first': [67,87,98,54], 'second': [5,6,8,9]}
df_2 = pd.DataFrame([dct_1, dct_2])
print(df_2)
a = pd.Series([9,8,3,4])
b = pd.Series(np.random.randint(1,5,4))
df_3 = pd.DataFrame({'first': a, 'second': b})
print(df_3)

matrix = np.random.randint(1, 12, (3,4))
print(pd.DataFrame(matrix, index = ['first', 'second', 'third']))

arr = np.array([1,2,32,4])
print(pd.DataFrame(arr))


   0
0  9
1  8
2  3
3  4
              first        second
0      [1, 2, 3, 4]  [5, 6, 8, 9]
1  [67, 87, 98, 54]  [5, 6, 8, 9]
   first  second
0      9       3
1      8       3
2      3       2
3      4       1
         0  1   2   3
first   10  6   4   2
second   9  6  10  11
third   11  8  10   5
    0
0   1
1   2
2  32
3   4


#### 3. Объедините два объекта Series с неодинаковыми множествами индексов так, чтобы вместо NaN было установлено значение 1.

In [115]:
a = pd.Series(np.random.randint(1,345, size=6))
b = pd.Series(np.random.randint(1,8, size = 4))
print(a)
df = pd.DataFrame({'first': a, 'second': b})
print(df)
df = df.fillna(1)
print(df)

0    344
1    218
2     71
3      1
4    216
5    155
dtype: int32
   first  second
0    344     3.0
1    218     2.0
2     71     1.0
3      1     1.0
4    216     NaN
5    155     NaN
   first  second
0    344     3.0
1    218     2.0
2     71     1.0
3      1     1.0
4    216     1.0
5    155     1.0


### 4. Переписать пример с транслированием для DataFrame так, чтобы вычитание происходило не по строкам, а по столбцам

In [136]:
matrix = pd.DataFrame(np.random.randint(1, 100, (3,4)), index = ['a', 'b', 'c'])
print(matrix)
c = matrix.loc[:,1].values.reshape(-1,1)
print(matrix - c)



    0   1   2   3
a  54  60  87  30
b  66  57  89  13
c   4  57  17  32
    0  1   2   3
a  -6  0  27 -30
b   9  0  32 -44
c -53  0 -40 -25
    0  1   2   3
a   0  0   0   0
b  12 -3   2 -17
c -50 -3 -70   2


### 5. На примере объектов DataFrame продемонстрировать использование методов ffill() и bfill()

In [145]:
group1 = {'Sasha': 18, 'Masha': 19, 'Danya': 23, 'Volodya': 15, 'Kate': 39}
group2 = { 'Sasha': 18, 'Danya': 23, 'Kate': 22}
df = pd.DataFrame({'group1': group1, 'group2': group2})
print(df)
print(df.ffill())
print(df.bfill())


         group1  group2
Sasha        18    18.0
Masha        19     NaN
Danya        23    23.0
Volodya      15     NaN
Kate         39    22.0
         group1  group2
Sasha        18    18.0
Masha        19    18.0
Danya        23    23.0
Volodya      15    23.0
Kate         39    22.0
         group1  group2
Sasha        18    18.0
Masha        19    23.0
Danya        23    23.0
Volodya      15    22.0
Kate         39    22.0


----
### Pandas

In [91]:
import pandas as pd

Пандас по сути расширение NumPy (структурированные массивы). Строки и столбцы индексируются метками, а не только числовыми значениями.  Основные структуры:  
1) Series  
2) DataFrame  
3) Index

Series

In [92]:
data = pd.Series([1,2,3,4])
print(data)
print(data.values) #сами данные
print(data.index) # индексы по которым происходит обращение
print(type(data.values))
print(type(data.index))

0    1
1    2
2    3
3    4
dtype: int64
[1 2 3 4]
RangeIndex(start=0, stop=4, step=1)
<class 'numpy.ndarray'>
<class 'pandas.core.indexes.range.RangeIndex'>


RangeIndex является итератором. Массив значений values является типом numpy array, index - pandas index

In [93]:
print(data[0])
print(data[1:3])

1
1    2
2    3
dtype: int64


Можно самостоятельно определить индекс у массива. При этом тип индекса становится pandas indexes. В качестве индексов может быть любой объект, в качестве срезов при этом можно также использовать эти объекты

Ведет себя как одномерный массив. Срезы можно задавать в явном и неявном виде(порядковый номер)

In [94]:
data = pd.Series([1,2,3,4], index = ['a', 'a', 'c', 'd'])
print(data)
print(data['a'])
print(data['c':'d'])
print(data[2:3])
print(type(data.index))



a    1
a    2
c    3
d    4
dtype: int64
a    1
a    2
dtype: int64
c    3
d    4
dtype: int64
c    3
dtype: int64
<class 'pandas.core.indexes.base.Index'>


Можно фильтровать данные по различным условиям. Также возможные некоторые функции словаря.

In [95]:
data = pd.Series([1,2,3,4], index = ['a', 'a', 'c', 'd'])
print('a' in data.index)
print('a' in data)
print(data.keys())
print(list(data.items()))
print(data[data > 2])

True
True
Index(['a', 'a', 'c', 'd'], dtype='object')
[('a', 1), ('a', 2), ('c', 3), ('d', 4)]
c    3
d    4
dtype: int64


Если в качестве index используются int'ы, необходимо использовать атрибуты индексаторы, чтобы показать системе, как разрешить обращение (к чему обращаться)

In [125]:
data = pd.Series([213213,323,312,544], index = [1, 2, 3, 4])
print(data)
print(data.loc[1])
print(data.iloc[1])

1    213213
2       323
3       312
4       544
dtype: int64
213213
323


Для создания Series можно использовать:  
1) Списки или массивы NumPy
2) Скалярные значения (будет повторять в заданном размере массива)
3) Словари

In [97]:
population = {
    'city1': 1000,
    'city2': 1001,
    'city3': 1002,
    'city4': 1003,
    'city5': 1004,
}
populate = pd.Series(population)
print(populate['city1'])
print(populate['city3':'city4'])

1000
city3    1002
city4    1003
dtype: int64


#### DataFrame

Является двумерным массивом с явно определенными индексами. Последовательность "согласованных" объектов Series.

Можно создавать через объекты:
1) Series
2) Списки словарей
3) Словари объектов Series
4) Двумерный массив NumPy
5) Структурированный массив NumPy

In [98]:
population = {
    'city1': 1000,
    'city2': 1001,
    'city3': 1002,
    'city4': 1003,
    'city5': 1004,
}

area = {
    'city1': 45678,
    'city2': 2345,
    'city3': 123456,
    'city4': 7890,
    'city5': 4567,
}

populate = pd.Series(population)
area = pd.Series(area)
states = pd.DataFrame({'population': populate, 'area': area})
print(states)
print(states.values)
print(states.index)
print(states.columns)
print(type(states.values), type(states.index), type(states.columns))

       population    area
city1        1000   45678
city2        1001    2345
city3        1002  123456
city4        1003    7890
city5        1004    4567
[[  1000  45678]
 [  1001   2345]
 [  1002 123456]
 [  1003   7890]
 [  1004   4567]]
Index(['city1', 'city2', 'city3', 'city4', 'city5'], dtype='object')
Index(['population', 'area'], dtype='object')
<class 'numpy.ndarray'> <class 'pandas.core.indexes.base.Index'> <class 'pandas.core.indexes.base.Index'>


In [99]:
print(states['area'])

city1     45678
city2      2345
city3    123456
city4      7890
city5      4567
Name: area, dtype: int64


Можно обращаться к столбцу через точку. Ведет себя как словарь или двумерный NumPy массив.

In [100]:
population = {
    'city1': 1000,
    'city2': 1001,
    'city3': 1002,
    'city4': 1003,
    'city5': 1004,
}

area = {
    'city1': 45678,
    'city2': 2345,
    'city3': 123456,
    'city4': 7890,
    'city5': 4567,
}

data = pd.DataFrame({'area': area, 'population': population})
print(data)
print(data['area'] is data.area)

data['new'] = data['area']
data['new1'] = data['area'] / data['population']
print(data)

         area  population
city1   45678        1000
city2    2345        1001
city3  123456        1002
city4    7890        1003
city5    4567        1004
True
         area  population     new        new1
city1   45678        1000   45678   45.678000
city2    2345        1001    2345    2.342657
city3  123456        1002  123456  123.209581
city4    7890        1003    7890    7.866401
city5    4567        1004    4567    4.548805


Можем выполнять операции над массивами с массивом значений. В срезах включаются концы срезов

In [101]:
population = {
    'city1': 1000,
    'city2': 1001,
    'city3': 1002,
    'city4': 1003,
    'city5': 1004,
}

area = {
    'city1': 45678,
    'city2': 2345,
    'city3': 123456,
    'city4': 7890,
    'city5': 4567,
}

data = pd.DataFrame({'area': area, 'population': population})
# data['new1'] = data['area'] / data['population']
# print(data.values, type(data.values))
# print(data.T)
print(data.values[0]) # обращение по строке
print(data.iloc[:2, 1:3])
print(data.loc[:'city2'])

[45678  1000]
       population
city1        1000
city2        1001
        area  population
city1  45678        1000
city2   2345        1001


Если некоторые элементы в Series не совпадают, то происходит объединение индексов. То есть отсутствующие значения в соответствующих индексах заменяются NaN. 

In [102]:
population = {
    'city1': 1000,
    'city2': 1001,
    'city3': 1002,
    'city4': 1003,
    'city10': 1004,
}

area = {
    'city1': 45678,
    'city2': 2345,
    'city3': 123456,
    'city4': 7890,
    'city7': 4567,
}

data = pd.DataFrame({'area': area, 'population': population})
print(data)

            area  population
city1    45678.0      1000.0
city2     2345.0      1001.0
city3   123456.0      1002.0
city4     7890.0      1003.0
city7     4567.0         NaN
city10       NaN      1004.0


#### Объединение датафреймов

In [103]:
import numpy as np
rng = np.random.default_rng()
dfA = pd.DataFrame(rng.integers(0,10,(2,2)), columns = ['a', 'b'])
dfB = pd.DataFrame(rng.integers(0,10,(3,3)), columns = ['a', 'b', 'c'])
dfC = dfA + dfB

print(dfC)

     a    b   c
0  2.0  7.0 NaN
1  2.0  5.0 NaN
2  NaN  NaN NaN


Создаем матрицу 3х4. В numpy и pandas используется $транслирование$. Например, вычтем из матрицы 3х4 строку 0, тогда от каждого значения соответственно будет вычтено это значение.

In [104]:
rng = np.random.default_rng(1)
A = rng.integers(0, 10, (3,4))
print(A)
print(A[0])
print(A - A[0])

df = pd.DataFrame(A, index = ['a', 'b', 'c'])
print(df - df.iloc[0])
print(df - df.iloc[0, ::2]) # нечетные не участвуют в вычислениях

[[4 5 7 9]
 [0 1 8 9]
 [2 3 8 4]]
[4 5 7 9]
[[ 0  0  0  0]
 [-4 -4  1  0]
 [-2 -2  1 -5]]
   0  1  2  3
a  0  0  0  0
b -4 -4  1  0
c -2 -2  1 -5
     0   1    2   3
a  0.0 NaN  0.0 NaN
b -4.0 NaN  1.0 NaN
c -2.0 NaN  1.0 NaN


### Объект Index
Это способ организации ссылки на данные объектов Series и DataFrame. Явялется неизменяемым и упорядочей(на самом деле каждый объект идет по порядку 1,2,3), также является мультимножеством (могут быть повторяющиеся значения)

Также индекс следует соглашениям объекта set (можно пересекать, объединять и т.д.)

In [105]:
ind = pd.Index([2,3,4,5,1,2])
print(ind[0])
print(ind[::2])
indA = pd.Index([1,2,3,4,5])
indB = pd.Index([7,3,4,5])
print(indA.intersection(indB))

2
Index([2, 4, 1], dtype='int64')
Index([3, 4, 5], dtype='int64')


???

In [106]:
import numpy as np
rng = np.random.default_rng()
s = pd.Series(rng.integers(0,10,4))

print(s)
print(np.exp(s))

0    5
1    0
2    0
3    4
dtype: int64
0    148.413159
1      1.000000
2      1.000000
3     54.598150
dtype: float64


NaN - not a number

NA - значения: NaN, null

Нужно уметь работать с отсутствующими значениями

В pandas два способа хранения отсутствующих значений:
1) Использование индикаторов - NaN, None 
2) null

None - Объект (накладные расходы). Не работает с агрегирующими операторами. Если присутствуют различные отсутствующие значения, можно их привести в NA с помощью dtype='int32'. 

Также можно использовать идентификацию таких элмеентов с помощью .notnull или .isnull. Избавиться от них можно с помощью .dropna(), также можно указать размерность, с которой осуществляем выбрасывание. С помощью параметра how(принимает параметры: all - строка и столбец отбрасывается, если отсутствуют все значения; any - хотя бы одно значение; thresh - порог = х, строка остается, если присутствует минимум х непустых значений)

In [107]:
x = pd.Series([1,2,3,np.nan,None,pd.NA])
x
print(x.isnull())
print(x.notnull())
print(x.dropna())

df = pd.DataFrame([[1,2,3,np.nan,None,pd.NA], [1,2,3,4,5], [np.nan,1,2,3]])
print(df.dropna(axis=1))

0    False
1    False
2    False
3     True
4     True
5     True
dtype: bool
0     True
1     True
2     True
3    False
4    False
5    False
dtype: bool
0    1
1    2
2    3
dtype: object
   1  2
0  2  3
1  2  3
2  1  2
